### ISSUE TITLE
PayPal notifications sample

### ISSUE THREAD

**Issue by technohowl** [paypal/PayPal-node-SDK#120]
I am running PayPal nodejs 'notifications' samples

**get_and_verify** returns 
```node notifications/webhook-events/get_and_verify.js
{ [Error: Response Status : 404]
  response:
   { name: 'INVALID_RESOURCE_ID',
     details: [],
     message: 'Resource id is invalid',
     httpStatusCode: 404 },
  httpStatusCode: 404 }
/.....path.../PayPal-node-SDK/samples/notifications/webhook-events/get_and_verify.js:12
        throw error;
              ^
Error: Response Status : 404
    at IncomingMessage.<anonymous> (/...path.../PayPal-node-SDK/lib/client.js:130:23)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)```


While **webhook_payload_verify.js** returns false.

What's wrong with the samples??

**Comment by avidas** [comment]
Are you running the samples as is or are you using an webhook event id that you have received in your app?

**Comment by technohowl** [comment]
HI Ananya,

I tried both the samples as well as the webhook id received in my web app.

For the sample I get the error that I posted in the first post.

For webhook event
