### ISSUE TITLE
error when executing the create method

### ISSUE THREAD

**Issue by Zhairgling** [paypal/PayPal-node-SDK#136]
hello i'm using express 4.13.3 with paypal rest sdk 0.6.4 and when i call the /create route i got : 

`[grunt-develop] > C:\Users\cauch\Dropbox\LesPasDeSo\node_modules\paypal-rest-sdk\lib\paypal-rest-sdk.js:208
                response.httpStatusCode = res.statusCode;
                                        ^

TypeError: Cannot assign to read only property 'httpStatusCode' of {"scope":"https://uri.paypal.com/services/subscriptions https://api.paypal.com/v1/payments/.* https://api.paypal.com/v1/vault/credit-card https://uri.paypal.com/services/applications/webhooks openid https://uri.paypal.com/payments/payouts https://api.paypal.com/v1/vault/credit-card/.*","nonce":"2016-02-13T14:50:20Zp01W3mqN0JbRV300hJbNDrSi3r4DNJTd5VpF3h2POik","access_token":"*********","token_type":"Bearer","app_id":"*******","expires_in":32378}
    at IncomingMessage.<anonymous> (C:\Users\cauch\Dropbox\LesPasDeSo\node_modules\paypal-rest-sdk\lib\paypal-rest-sdk.js:208:41)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:450:9)
    at process._tickCallback (node.js:364:17)
>> application exited with code 1`

here is my code : 

`var express = require('express');
var router = express.Router();
var paypal = require('paypal-rest-sdk');

/* GET home page. */

router.get('/', function(req, res) {

var create_payment_json = {
    "intent": "sale",
    "payer": {
        "payment_method": "paypal"
    },
    "redirect_urls": {
        "return_url": "http://return.url",
        "cancel_url": "http://cancel.url"
    },
    "transactions": [{
        "item_list": {
            "items": [{
                "name": "item",
                "sku": "item",
                "price": "1.00",
                "currency": "USD",
                "quantity": 1
            }]
        },
        "amount": {
            "currency": "USD",
            "total": "1.00"
        },
        "description": "This is the payment description."
    }]
};

paypal.payment.create(create_payment_json, function (error, payment) {
    if (error) {
        throw error;
    } else {
        console.log("Create Payment Response");
        console.log(payment);
    }
});

});

module.exports = router;
`

thanks for help

**Comment by bluk** [comment]
@Zhairgling Can you try a later version of the PayPal SDK? 0.6.4 is really old (we're on `1.6.8` right now). I think some of the assumptions in 0.6.4 are not compatible with Express 4.x (which was released after 0.6.4).

**Comment by ppmtscory** [comment]
Closing due to inactivity.  If your issue persists after upgrading, please feel free to reopen or open a new issue.  Thanks.

**Comment by Zhairgling** [comment]
Yeah thanks that working better
