### ISSUE TITLE
creditCard.create() response is DUPLICATE_REQUEST_ID

### ISSUE THREAD

**Issue by gustavLatte** [paypal/PayPal-node-SDK#222]
### General Information

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs): af4506ac6c040
- Version of node.js used: 6.7.0
- SDK Version: 1.7.0

### Issue Description

Hello,

I'm trying to store credit card using the SDK and I keep getting the same error "DUPLICATE_REQUEST_ID".
I don't override the request id header, even though I tried but I kept getting this error. Diving into the SDK code I found that the  basic URL is not as in the documentation **/v1/vault/credit-card/** and not **/v1/vault/credit-cards** ([SDK](https://github.com/paypal/PayPal-node-SDK/blob/master/lib/resources/CreditCard.js) Vs. [Doc.](https://developer.paypal.com/docs/api/vault/)).

I tried to change it but I kept getting the same response. 
Then I tried different **payment.create** and it works just fine.

the complete error response:

{ Error: Response Status : 400
paypal-provider.js:118
    at IncomingMessage.<anonymous> (\node_modules\paypal-rest-sdk\lib\client.js:136:23)
                throw error;
    at emitNone (events.js:91:20)
                ^
    at IncomingMessage.emit (events.js:185:7)

    at endReadableNT (_stream_readable.js:974:12)
Error: Response Status : 400
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
    at IncomingMessage.<anonymous> (D:\GIT\cd_api\node_modules\paypal-rest-sdk\lib\client.js:136:23)
  response: 
   { name: 'DUPLICATE_REQUEST_ID',
    at emitNone (events.js:91:20)
     debug_id: 'af4506ac6c040',
    at IncomingMessage.emit (events.js:185:7)
     message: 'The value of PayPal-Request-Id header has already been used',
     information_link: 'https://developer.paypal.com/docs/api/#DUPLICATE_REQUEST_ID',
    at endReadableNT (_stream_readable.js:974:12)
     httpStatusCode: 400 },
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
  response_stringified: '{"name":"DUPLICATE_REQUEST_ID","debug_id":"af4506ac6c040","message":"The value of PayPal-Request-Id header has already been used","information_link":"https://developer.paypal.com/docs/api/#DUPLICATE_REQUEST_ID","httpStatusCode":400}',
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  httpStatusCode: 400 }

**Comment by ankit-clicklabs** [comment]
I am facing the same problem in the sandbox mode. It was working fine earlier but now  suddenly this error has started coming up when I try to add a card.

**Comment by jaypatel512** [comment]
Hey @gustavLatte @ankit-clicklabs ! Are you seeing this error only in 1.7.0 ? Can you test it pretty quick if 1.6.9 was having the same issue ? trying to narrow down the root cause. We had some issues with sandbox on weekend where it was having some issues. It should be working properly now. Please let me know.

**Comment by bluk** [comment]
Closing due to inactivity. If this is still an issue, please leave a comment, and we'll reopen. Thanks!

**Comment by ndenkha** [comment]
This just started happening to me today with SDK 1.8.0, when creating credit cards.
This can't be a URL issue as explained on here. How do you recover from this?

The remote server returned an error: (400) Bad Request.
DUPLICATE_REQUEST_ID
The value of PayPal-Request-Id header has already been used

**Comment by ndenkha** [comment]
Just so I'd update this, I had to explicitly set the PayPal-Request-Id in the ApiContext's HttpHeader as shown. This doesn't make sense cause the ApiContext already has the RequestId which gets set to a random value upon instantiation, so I don't know why there are 2 such fields.


private Dictionary<string, string> GetApiContextHeader()
        {
            var dicHeader = new Dictionary<string, string>();
            dicHeader.Add("PayPal-Request-Id", Guid.NewGuid().ToString());

            return dicHeader;
        }

        private void SetApiContextHeaders()
        {
            var dicHeaders = GetApiContextHeader();
            _apiContext.HTTPHeaders = dicHeaders;
        }

**Comment by xiaoleih41** [comment]
@ndenkha Please open a new ticket with the **debugId** of your API call. Also, direct credit card processing on REST API are being deprecated. Please consider to use Braintree SDK from [braintree.com](https://www.braintreepayments.com/products/braintree-direct) going forward for your credit card processing needs.
