### ISSUE TITLE
Error: Invalid JSON Response Received

### ISSUE THREAD

**Issue by WayneUong** [paypal/PayPal-node-SDK#285]
### General information

* SDK/Library version: 1.7.1
* Environment: Production
* `PayPal-Debug-ID` values: 6775d91b7254d, 6775d91b7254d
* Language, language version, and OS: OSX

### Issue description
While activate/update plan, I received this error:

```
W20170724-15:58:09.824(-7)? (STDERR) 2017-07-24T22:58:09.821Z - error:  Error: Invalid JSON Response Received. If the response received is empty, please checkthe httpStatusCode attribute of error message for 401 or 403. It is possible that the client credentialsare invalid for the environment you are using, be it live or sandbox.
W20170724-15:58:09.824(-7)? (STDERR)     at IncomingMessage.<anonymous> (/Users/wayneuong/nfc-meteor/node_modules/paypal-rest-sdk/lib/client.js:124:23)
W20170724-15:58:09.825(-7)? (STDERR)     at emitNone (events.js:72:20)
W20170724-15:58:09.825(-7)? (STDERR)     at IncomingMessage.emit (events.js:166:7)
W20170724-15:58:09.825(-7)? (STDERR)     at endReadableNT (_stream_readable.js:923:12)
W20170724-15:58:09.826(-7)? (STDERR)     at nextTickCallbackWith2Args (node.js:511:9)
W20170724-15:58:09.826(-7)? (STDERR)     at process._tickCallback (node.js:425:17)
```

**Comment by pp-randy** [comment]
Thank you for reporting the issue. It appears this issue is impacting other SDKs are well, I have created an issue here for tracking https://github.com/paypal/PayPal-REST-API-issues/issues/120, please follow this issue for further updates.
