### ISSUE TITLE
Authorization code not found in cache

### ISSUE THREAD

**Issue by tranchuong** [paypal/PayPal-node-SDK#300]
### General information

* SDK/Library version: 1.7.1
* Environment: Sandbox
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: node.js 6.9.1 on MacOs

### Issue description
I have an issue when run test with authorization_code. 
authorization_code is code generate from [iOS SDK](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/future_payments_mobile.md#obtain-customer-consent) 

```
var paypal = require('../');
require('./configure');

describe('SDK', function () {
    this.timeout(50000);
    describe('#generateToken', function () {
        it('token should be generated', function (done) {
            var authorization_code = 'C21AAFMLDLDqtYuRHiWQBO2XXSRTb5mfBZ0W1Zw3P55t42CG6f97iK1srF4sp-Bl_fOfGBHXl3S-K7UoeNaJuaEcw-zc2pTDg';
            var config = { 'authorization_code': authorization_code };
            paypal.generateToken(config, function (error, token) {
                
                console.log(error);                
                console.log(token);
                done();
            });
        });
    });
});

```

**Log error**:
```
{ Error: Response Status : 401
    at IncomingMessage.<anonymous> (/Users/Sam/Downloads/PayPal-node-SDK-master/lib/client.js:130:23)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  response:
   { error: 'invalid_authz_code',
     error_description: 'Authorization code not found in cache',
     httpStatusCode: 401 },
  httpStatusCode: 401 }
```

I run a test with curl. It's fine
```
curl 'https://api.sandbox.paypal.com/v1/oauth2/token' \
    -H "Content-Type: application/x-www-form-urlencoded" \
    -u "AVKG5cV11yN7sUuLcx9j62MGRNCcccL9aMNA6pV6fWhWDShbvUdRhH_2ItxnCZ48LSqxUTo4K1bC-P2O:EJ0c_g9c-SW-j7tpItubqCB0x3nGDYOasgI3wLFaU7idO4a3kDivqvFIU53tNNeqgLOEINL3dsfSOvxU" \
    -d 'grant_type=client_credentials&response_type=token&redirect_uri=urn:ietf:wg:oauth:2.0:oob&code=C21AAFMLDLDqtYuRHiWQBO2XXSRTb5mfBZ0W1Zw3P55t42CG6f97iK1srF4sp-Bl_fOfGBHXl3S-K7UoeNaJuaEcw-zc2pTDg'

```
**Result test with curl**
```
{
  "scope": "https://uri.paypal.com/services/subscriptions https://uri.paypal.com/services/paypalhere https://api.paypal.com/v1/payments/.* https://api.paypal.com/v1/vault/credit-card https://api.paypal.com/v1/payments/sale/.*/refund https://uri.paypal.com/services/applications/webhooks openid https://uri.paypal.com/payments/payouts https://api.paypal.com/v1/vault/credit-card/.* https://api.paypal.com/v1/payments/refund",
  "nonce": "2017-08-31T04:33:16ZcAZUQxrUrtPB8r0xKo_glpk4FENPDxxuXhguVCEWOLs",
  "access_token": "A21AAFQggWitpm6eJD9ut1euCLQxdMmalDnE0R7btPr_YxLAKIGAs8k_HaZs4Xlwi9PcQUNZSblRUckkxzHxp6tPABSNMrA3A",
  "token_type": "Bearer",
  "app_id": "APP-80W284485P519543T",
  "expires_in": 30947
}
```

**Comment by tranchuong** [comment]
I find a different **grant_type** when I log payload in file api.js line 52

**Run example**:
`grant_type=authorization_code&response_type=token&redirect_uri=urn:ietf:wg:oauth:2.0:oob&code=C21AAFMLDLDqtYuRHiWQBO2XXSRTb5mfBZ0W1Zw3P55t42CG6f97iK1srF4sp-Bl_fOfGBHXl3S-K7UoeNaJuaEcw-zc2pTDg`

**Run curl**:
`grant_type=client_credentials&response_type=token&redirect_uri=urn:ietf:wg:oauth:2.0:oob&code=C21AAFMLDLDqtYuRHiWQBO2XXSRTb5mfBZ0W1Zw3P55t42CG6f97iK1srF4sp-Bl_fOfGBHXl3S-K7UoeNaJuaEcw-zc2pTDg`

How to solve the problem?

**Comment by tranchuong** [comment]
I try to edit code in file api.js

line 54:         `payload = 'grant_type=client_credentials&response_type=token&redirect_uri=urn:ietf:wg:oauth:2.0:oob&code=' + config.authorization_code;`

and line 84: `if (config.authorization_code) {`

```
var generateToken = exports.generateToken = function generateToken(config, cb) {

    if (typeof config === "function") {
        cb = config;
        config = configuration.default_options;
    } else if (!config) {
        config = configuration.default_options;
    } else {
        config = utils.merge(config, configuration.default_options, true);
    }
    console.log(config);

    var payload = 'grant_type=client_credentials';
    if (config.authorization_code) {
        payload = 'grant_type=client_credentials&response_type=token&redirect_uri=urn:ietf:wg:oauth:2.0:oob&code=' + config.authorization_code;
    } else if (config.refresh_token) {
        payload = 'grant_type=refresh_token&refresh_token=' + config.refresh_token;
    }

    console.log('payload: '+ payload);

    var basicAuthString = 'Basic ' + new Buffer(config.client_id + ':' + config.client_secret).toString('base64');

    var http_options = {
        schema: config.schema || configuration.default_options.schema,
        host: config.host || utils.getDefaultApiEndpoint(config.mode) || configuration.default_options.host,
        port: config.port || configuration.default_options.port,
        headers: utils.merge({
            'Authorization': basicAuthString,
            'Accept': 'application/json',
            'Content-Type': 'application/x-www-form-urlencoded'
        }, configuration.default_options.headers, true)
    };

    client.invoke('POST', '/v1/oauth2/token', payload, http_options, function (err, res) {
        var token = null;
        console.log(res);
        if (res) {
            if (!config.authorization_code && !config.refresh_token) {
                var seconds = new Date().getTime() / 1000;
                token_persist[config.client_id] = res;
                token_persist[config.client_id].created_at = seconds;
            }

            if (config.authorization_code) {
                token = res.token_type + ' ' + res.access_token;
            }
            else {
                token = res.refresh_token;
            }
        }
        cb(err, token);
    });
};

```

**Comment by tranchuong** [comment]
> The authorization code is very short-lived. You should exchange it for a refresh and access token immediately.
[exchange-authorization-code-for-refresh--access-tokens](https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/future_payments_server.md#exchange-authorization-code-for-refresh--access-tokens)

It's mean that **authorization-code** exchange **access token** 1 time. 

Solved
