### ISSUE TITLE
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters

### ISSUE THREAD

**Issue by shrimank** [paypal/PayPal-node-SDK#349]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description
After creating payment, when iteratin the response getting below error

## TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:127:13)
    at Object.request (https.js:245:10)
    at Object.invoke (/data/RANDD/TAG/Amazon/pay-pal-rest-sdk/node_modules/paypal-rest-sdk/lib/client.js:74:22)
    at Object.executeHttp (/data/RANDD/TAG/Amazon/pay-pal-rest-sdk/node_modules/paypal-rest-sdk/lib/api.js:148:16)
    at Object.execute (/data/RANDD/TAG/Amazon/pay-pal-rest-sdk/node_modules/paypal-rest-sdk/lib/resources/Payment.js:26:17)
    at app.get (/data/RANDD/TAG/Amazon/pay-pal-rest-sdk/app.js:90:20)
    at Layer.handle [as handle_request] (/data/RANDD/TAG/Amazon/pay-pal-rest-sdk/node_modules/express/lib/router/layer.js:95:5)
    at next (/data/RANDD/TAG/Amazon/pay-pal-rest-sdk/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/data/RANDD/TAG/Amazon/pay-pal-rest-sdk/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/data/RANDD/TAG/Amazon/pay-pal-rest-sdk/node_modules/express/lib/router/layer.js:95:5)

**Comment by xiaoleih41** [comment]
Which version of SDK are you using? Are you using our [2.0 beta version] (https://github.com/paypal/PayPal-node-SDK/tree/2.0-beta)

**Comment by shrimank** [comment]
I  was missing paymentId  parameter when executing the payment,
resolved myself
Thank you.
