### ISSUE TITLE
Getting internal service error : sandbox

### ISSUE THREAD

**Issue by mitulparmar21696** [paypal/PayPal-node-SDK#360]
{ Error: Response Status : 500
at IncomingMessage. (/var/www/html/wiss/wissenxweb/node_modules/paypal-rest-sdk/lib/client.js:130:23)
at emitNone (events.js:111:20)
at IncomingMessage.emit (events.js:208:7)
at endReadableNT (_stream_readable.js:1056:12)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickDomainCallback (internal/process/next_tick.js:218:9)
response:
{ name: 'INTERNAL_SERVICE_ERROR',
message: 'An internal service error occurred.',
information_link: 'https://developer.paypal.com/docs/api/payments/#errors',
debug_id: 'c42e829d5a6f8',
httpStatusCode: 500 },
httpStatusCode: 500 }

Environment: Sandbox
PayPal-Debug-ID values: c42e829d5a6f8
Language, language version, and OS:NodeJS
Issue description
When submitting payments via credit or debit card it gives internal service error like above

**Comment by dadsquatch** [comment]
Same. 

Did some testing with a sample object to make sure it was hitting the API, passing their validation checks, and narrowed it down to being something on their side from what I can see. When everything is correct in my sample API and get's passed their validation steps (amount.total must equal amount.details blah blah) is where I am getting the 500 too. 

Following for resolution.
