### ISSUE TITLE
'MALFORMED_REQUEST' for update billing plans

### ISSUE THREAD

**Issue by arthurtalkgoal** [paypal/PayPal-node-SDK#73]
I wanna active my billing plans via update, but it returned Malformed request, seems that someone in the Php got similar problem. it is related to the ```PATCH``` request wrong parameter:

http://stackoverflow.com/questions/25602097/paypal-rest-api-activate-billing-plan

My codes ---
````
 var options = [{
        "path": "/",
        "values": update_values,
        "op": "replace",
      }],
      billingPlanId = self.subscription.billingPlanId;
          paypal.billingPlan.update(billingPlanId, options, function (error, response) {
              if (error) {
                  console.log(error.response);
                  return next(null, error);
              } else if (response.httpStatusCode == 200) {
                  self.subscription.paypal_activated = true;
                  return next(response);
              } 
              return next(null, "Unexpected Error");
          });

```


I captured the data in ```lib/generate.js```
```
update: function update(id, data, config, cb) {
console.log("config is ")
console.log(this.baseURL + id)     
console.log(config)      
console.log(data)      
        api.executeHttp('PATCH', this.baseURL + id, data, config, cb);
    },
```

The output is
```
config is
/v1/payments/billing-plans/P-1xxx569444D761401YBTP75JI
[Function]
[ { path: '/', values: { state: 'ACTIVE' }, op: 'replace' } ]
http_options is ----------
/v1/payments/billing-plans/P-1xxx69444D761401YBTP75JI
[ { path: '/', values: { state: 'ACTIVE' }, op: 'replace' } ]
{ mode: 'sandbox',
  schema: 'https',
  host: 'api.sandbox.paypal.com',
  port: '',
  openid_connect_schema: 'https',
  openid_connect_host: 'api.sandbox.paypal.com',
  openid_connect_port: '',
  authorize_url: 'https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/authorize',
  logout_url: 'https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/endsession',
  headers: {},
  client_id: 'AYxDPRPEsuZSlhmMMlqD2KwQ9kzT3wwaRkHj3sFb_5vu537FvLEKrHaSdNRrQSIomxwD3byICMJiwonb',
  client_secret: 'EBIH0XQVQb3r1m5ZIigz9QYe565fTsnqSEVwYVy1C2dOvwA_wHfbavPhLkz7mxBC90eLXNT4fA-VFYa7' }
```
Error Got 
```
{ name: 'MALFORMED_REQUEST',
  message: 'Incoming JSON request does not map to API request',
  information_link: 'https://developer.paypal.com/webapps/developer/docs/api/#MALFORMED_REQUEST',
  debug_id: 'c4852d7ab0da5',
  httpStatusCode: 400 }
Error: Response Status : 400
    at IncomingMessage.<anonymous> (/myhome/node_modules/paypal-rest-sdk/lib/client.js:117:23)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

**Comment by arthurtalkgoal** [comment]
Oops, I tried to update the npm then the problem gone.

Let me know if you guys need more data to fix that.
