### ISSUE TITLE
Long running paypal gives errors

### ISSUE THREAD

**Issue by thomaschaaf** [paypal/PayPal-node-SDK#77]
Hello,

I am using the latest 1.5.1 release. But I am having trouble if our server process has been running for a while. The first request after having the application run for a day will always fail like this:

```
2015-03-26 11:06 +00:00: 2015-03-26T11:06:32.014Z - error:  Error: Invalid JSON Response Received
  at IncomingMessage.<anonymous> (/opt/prisma-cloud/releases/20150326083347/node_modules/paypal-rest-sdk/lib/client.js:104:23)
  at IncomingMessage.emit (events.js:129:20)
  at IncomingMessage.wrapped (/opt/prisma-cloud/releases/20150326083347/node_modules/newrelic/lib/transaction/tracer/index.js:156:28)
  at IncomingMessage.wrappedEmit [as emit] (/opt/prisma-cloud/releases/20150326083347/node_modules/newrelic/lib/transaction/tracer/index.js:188:46)
  at _stream_readable.js:908:16
  at wrapped (/opt/prisma-cloud/releases/20150326083347/node_modules/newrelic/lib/transaction/tracer/index.js:156:28)
  at _tickDomainCallback (node.js:381:11)
  at process.nextTickWrapper (/opt/prisma-cloud/releases/20150326083347/node_modules/newrelic/lib/instrumentation/core/timers.js:12:14)
```

The second request will work. Then again after a day for example it will fail again and work afterwards. This behaviour lets me think that maybe this is due to a 401 being received and the token being refreshed.

The paypal.payment.create request we are sending out has the following request:
```
{ intent: 'sale',
  payer: { payment_method: 'paypal' },
  redirect_urls:
   { return_url: 'http://komola.prismabox.de/viewer/2529/checkout/confirmation',
     cancel_url: 'http://komola.prismabox.de/viewer/2529/checkout/payment' },
  transactions:
   [ { description: 'Your photo order.',
       amount: { currency: 'EUR', total: '1.00' } } ] }
```

How can we trace this? Is there a way for me to disable a token to be able to test the behaviour? Waiting 24 hours between each test is not really something I would like to do..

**Comment by avidas** [comment]
@thomaschaaf are you using the sdk for just one merchant? i.e. one pair of client_id/client_secret. How are you doing the configuration of the sdk?

**Comment by avidas** [comment]
Another possible debugging option, a lot of the token persistence to improve sdk performances got in version v1.4.0 , so if possible at all, it might be worth trying out v1.3.1 to see if the issue persists.

**Comment by thomaschaaf** [comment]
Thanks for the replies.

I will try both and see if it helps.

**Comment by avidas** [comment]
Hey, is this problem still happening?

**Comment by avidas** [comment]
Closing, reopen if problem still happening.
